### ISSUE TITLE
Attribution or Copyright is missing

### ISSUE THREAD

**Issue by bytefish** [ducke/NancyApiTokenAuth#1]
It would be great to give some credit or leave a copyright statement in place, when using large portions of the source code from my blog.

The blog post is located at:
- [http://bytefish.de/blog/token_authentication_owin_nancy](http://bytefish.de/blog/token_authentication_owin_nancy/)

The source code is available at:
- [https://github.com/bytefish/NancyOwinExample](https://github.com/bytefish/NancyOwinExample)

I am adding a link to the project in the blog post. I have noticed it is missing there.

**Comment by ducke** [comment]
Sorry I've taken so long to reply! You are totaly correct. I added the missing credits.
Thanks for the great blog post!
